### ISSUE TITLE
Make missile lifetime dependant on distance travelled

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#11]
The current implementation for missile despawning is to have missiles despawn after 10s. This means that they go way too far, and will go even farther once speed upgrades are implemented. 

The easiest way to tackle this would be to modify [`systems::missile::cull`][1] to cull based on distance from the starting point. This approach would require adding a new system that reads from `OnMissileFire` to add the initial missile position, then using that initial position in [`systems::missile::cull`][1].

[1]: ../tree/master/server/src/systems/missile/cull.rs
[2]: ../tree/master/server/src/systems/missile/fire.rs

**Comment by xyz-airmash** [comment]
I started working on this but ran into a wall with the units system. Will probably need a bit of hand holding.
