### ISSUE TITLE
possible to get stuck in spec after dying

### ISSUE THREAD

**Issue by ghost** [steamroller-airmash/airmash-server#110]
Not much information -- Lr got stuck somehow after dying, or after entering spectate. Had to reconnect

Attempting to leave spectate produces the message in the log: "respawn denied - 2s cooldown after death".

Looks like that value might be set to a crazy number, or perhaps missing and/or the logic is bad

**Comment by steamroller-airmash** [comment]
I believe that this should be fixed as part of the changes that got rolled into #116
