### ISSUE TITLE
No health and regen indicators

### ISSUE THREAD

**Issue by BlackCrawler** [steamroller-airmash/airmash-server#130]
TY! You are a ctf-saver
Latest master on europe ctf.
Health and regen indicators disappear after death. And the spectator mode button doesn't.
![ctf](https://user-images.githubusercontent.com/27617921/62738365-d40cf800-ba3a-11e9-9eb2-785f24fa123c.png)

**Comment by steamroller-airmash** [comment]
I was able to repro this in FFA as well by flying far enough away from my respawn point. Fixed now though, sorry for taking so long :(
