### ISSUE TITLE
Determine `SERVER_CUSTOM` data for BTR

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#5]
Pretty much as the title says. `SERVER_CUSTOM` is used to send data about the end of the game. This data varies for each game type and is stored as JSON in the `data` field of the packet.

To get at this info, overriding `Players.network` and dumping all `SERVER_CUSTOM` packets should be sufficient.

For reference here is the packet definition:
```js
[A.SERVER_CUSTOM]: [
    ["type", I.uint8], 
    ["data", I.textbig]
]
```

**Comment by xyz-airmash** [comment]
The `SERVER_CUSTOM` packet appears to not get sent during BTR. Typing this in the console yields nothing. I could be wrong though.

```js
const _PlayersNetwork = Players.network;
Players.network = (type, data) => {
  if (type === Network.SERVERPACKET.SERVER_CUSTOM) {
    console.log(data);
  }
  return _PlayersNetwork(type, data);
}
```

**Comment by steamroller-airmash** [comment]
I'd have to look through the game source to confirm, but I'm not sure that the `type` parameter corresponds to the packet type. I ran a bot get some data from a BTR match and got the following packet
```json
{
    "c":"SERVER_CUSTOM",
    "type":1,
    "data":"{\"p\":\"STEAMROLLER\",\"f\":122,\"b\":4000,\"k\":3,\"t\":13}"
}
```
The `p` fields appears to be the winner's name, and `t` is probably the amount of time that the notice should be displayed (as with CTF). `b` is most likely the amount of bounty awarded to the winner (same as CTF again). 

That leaves `k` and `f`. I think `k` would be the number of kills, but I have no idea what `f`represents. It might be worth looking further at what the game code does to fully determine what the fields mean.

**Comment by derps-airmash** [comment]
f is the flag country code:

```javascript
    Games.showBTRWin = function(e) {
        if (!$("#custom-msg").length) {
            var t = '<div id="custom-msg" class="btrwin"><div class="trophy"></div><div class="winner"><div class="player"><span class="flag big flag-' + e.f + '"></span>' + UI.escapeHTML(e.p) + '</div></div><div class="bounty"><span class="stat">' + e.k + " KILL" + (1 == e.k ? "" : "S") + "</span>+" + e.b + " BOUNTY</div></div>";
            $("body").append(t),
            UI.showPanel("#custom-msg"),
            setTimeout(function() {
                UI.hidePanel("#custom-msg", !1, !0)
            }, 1e3 * e.t),
            Sound.gameComplete()
        }
    }

```

**Comment by steamroller-airmash** [comment]
I've created serialization bindings for this [here](https://docs.rs/airmash-protocol/0.2.3/airmash_protocol/custom/index.html). Closing as all the work is done here.
