### ISSUE TITLE
Implement shield spawning

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#57]
I suspect that this will need to be done separately for each game mode. For each one there's a few things that need to be determined:

1. The general distribution and frequency of shield spawns across the whole map.
2. The location of any specific shields on the map (e.g. base shields in CTF)

It might be possible to generalize 1. across all game modes, but 2. will definitely be different for each one.

The easiest way to go about this is to create a system that sends events into a `ShieldSpawn` channel (I'll create this in the next few days and update this issue once it's done).

When determining the general positions of all the shields, [the STATSBOT logs](https://tiny.cc/airmash-stats) might be helpful for raw data. I'm not sure if they have these events, but they might be helpful if they do

**Comment by usopp-airmash** [comment]
There are too many shields in FFA right now.
Could you make the respawn period of the shield in FFA to be approx 2min? This reduces the number of shields to 1

**Comment by steamroller-airmash** [comment]
I've pushed a commit that will halve the shield spawning rate. It'll take a bit for the update to reach the server (it has to get to @derps-airmash 's repos and then up to the server). Hopefully this will bring the number of shields in FFA to more reasonable levels.

If this isn't enough open a new issue and we can continue to tweak it.
